#!/usr/bin/env bash
# Stop hook: auto-commit pending changes with a commitlint-compliant message
# generated by `claude -p`. Skipped on protected branches and when nothing
# would be committed.
set -euo pipefail

log() { printf '[auto-commit] %s\n' "$*" >&2; }

# Read the Stop hook payload (we only need stop_hook_active for loop guard).
payload="$(cat || true)"
if printf '%s' "$payload" | grep -q '"stop_hook_active"[[:space:]]*:[[:space:]]*true'; then
  exit 0
fi

repo_root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || true)}"
if [ -z "$repo_root" ] || [ ! -d "$repo_root/.git" ]; then
  exit 0
fi
cd "$repo_root"

branch="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
case "$branch" in
  ""|master|main|develop)
    log "skip: branch '$branch' is protected or detached"
    exit 0
    ;;
esac

# Quick existence check: anything to commit (tracked or untracked)?
if git diff --quiet HEAD -- && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  exit 0
fi

# Stage everything (respecting .gitignore) so the diff for the LLM matches what we'll commit.
git add -A
if git diff --cached --quiet; then
  exit 0
fi

diff="$(git diff --cached --no-color --stat --patch | head -c 60000)"
if [ -z "$diff" ]; then
  exit 0
fi

prompt='You generate Conventional Commits messages for a `git commit`.

Rules (commitlint compatible):
- Format: `<type>(<scope>): <short description>` followed by an optional body separated by a blank line.
- Allowed types: build, ci, docs, feat, fix, perf, chore, refactor, revert, format, test.
- Subject must be <= 72 characters.
- If the subject starts with an English word, it must be lowercase (e.g. `feat`, not `Feat`).
- Output ONLY the commit message text. No code fences, no preamble, no trailing commentary.

Below is the staged diff. Write the commit message for it.

--- BEGIN DIFF ---
'"$diff"'
--- END DIFF ---'

if ! command -v claude >/dev/null 2>&1; then
  log "skip: claude CLI not on PATH"
  exit 0
fi

# `--bare` skips hooks/CLAUDE.md/MCP so this nested call cannot re-trigger us.
# `--allowedTools ""` blocks tool use; we only want text generation.
msg="$(printf '%s' "$prompt" | claude --bare -p --output-format text --allowedTools "" 2>/dev/null || true)"
msg="$(printf '%s' "$msg" | sed -e 's/^[[:space:]]*//' -e '/./,$!d' | awk 'NF || p; { if (NF) p=1 }')"

if [ -z "$msg" ]; then
  log "skip: empty message from claude"
  exit 0
fi

# Basic commitlint sanity: must start with type(scope?): or type:
if ! printf '%s' "$msg" | head -1 | grep -Eq '^(build|ci|docs|feat|fix|perf|chore|refactor|revert|format|test)(\([^)]+\))?: .+'; then
  log "skip: generated message does not look like Conventional Commits:"
  log "$(printf '%s' "$msg" | head -3)"
  exit 0
fi

git -c commit.gpgSign=false commit -m "$msg" >/dev/null
log "committed: $(printf '%s' "$msg" | head -1)"
