services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - ../config.ini:/home/vscode/.gamdl/config.ini
      - venv:/home/vscode/app/.venv
    tty: true
    stdin_open: true

volumes:
  venv:
    driver: local
